# <font color=#0404B4>**ĐỒ ÁN THỰC HÀNH - NHẬP MÔN KHOA HỌC DỮ LIỆU** </font>

### <font color=#0404B4> Bảng thành viên nhóm 7 </font>
|<center><div style="width:150px">MSSV</div><center>|<center><div style="width:290px">Họ và tên</div><center>|
|---------- |:-------------:|
| <center>20120041<center>  | <center>Trần Kim Bảo<center> |
| <center>20120053<center>  |   <center>Nguyễn Thành Đạt<center>   | 
| <center>20120071<center>  |<center>Nguyễn Thị Bích Hà<center> |
| <center>20120084<center>  | <center>Nguyễn Văn Hiếu<center> |
| <center>20120113<center>  | <center>Lê Nguyên Khang<center> |

In [3]:
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()
import math
import copy
# from pandas.testing import assert_frame_equal # to compare two dataframes
# YOUR CODE HERE (OPTION) 
# Nếu cần các thư viện khác thì bạn có thể import thêm tại đây

# <font color=#0404B4>Table of Contents</font>
1. [Thu thập dữ liệu](#1)
2. [Khám phá và tiền xử lý dữ liệu](#2)
3. [Mỗi cột hiện đang có kiểu dữ liệu gì? Có cột nào có kiểu dữ liệu chưa phù hợp?](#3)
4. [Với mỗi cột, các giá trị được phân bố như thế nào?](#4)

<a name="1"></a>
# <font color=#0404B4> A. Thu thập dữ liệu</font>

### Tại sao lại chọn bộ dữ liệu này?
- Đại dịch Covid-19 vừa qua đã gây nhiều ảnh hưởng, tác động tích cực lẫn tiêu cực lên đời sống của con người. Do đó, nhiều cuộc khảo sát và phân tích đã diễn ra trong suốt quá trình dịch hoành hành và cả sau khi đại dịch giảm bớt. Đặc biệt, đối với đất nước Ấn Độ, đại dịch Covid-19 đã để lại những hậu quả nặng nề, người chết nhiều vô số kể do điều kiện chăm sóc và kinh tế của đất nước này. Với sự tò mò, nhóm đã đặc biệt quan tâm đến tình hình của Ấn Độ hơn so với những đất nước tiên tiến và phát triển khác. Và đối với của đất nước này, nhóm cảm thấy khá thú vị trong việc tìm hiểu và khai thác về mặt giáo dục lẫn sức khỏe tinh thần của sinh viên, học sinh trong hoàn cảnh phải đối mặt với cơn đại dịch. Vì thế, nhóm đã chọn khai thác bộ dữ liệu về vấn đề nêu trên, để phân tích sâu hơn tình hình ở thời điểm hiện tại (năm 2020) khi Covid-19 bùng phát trên đất nước Ấn Độ. 

### Nguồn gốc và giấy phép sử dụng của bộ dữ liệu?
- Nhóm sử dụng dữ liệu [**COVID-19 Survey Student Responses.csv**](https://www.kaggle.com/datasets/kunal28chaturvedi/covid19-and-its-impact-on-students)
- Tập dữ liệu mô tả Tác động của đợt bùng phát COVID-19 đối với Giáo dục, Sức khỏe tâm thần và Thói quen hàng ngày. Trong nghiên cứu này, một cuộc khảo sát cắt ngang (cross-sectional survey) được tiến hành với 1182 sinh viên thuộc các nhóm tuổi khác nhau đến từ các cơ sở giáo dục khác nhau ở vùng Thủ đô Quốc gia Delhi (NCR) - Ấn Độ vào năm 2020.
- LICENSE của dữ liệu là [**CC0: Public Domain**](https://creativecommons.org/publicdomain/zero/1.0/) - người dùng được phép sử dụng với mục đích phi thương mại và phải credit cho chủ sở hữu.
- Người ta thu thập dữ liệu bằng cách thực hiện khảo sát trên giấy.

<a name="2"></a>
# <font color=#0404B4> B. Khám phá và tiền xử lý dữ liệu</font>

## 1. Đọc dữ liệu từ file

In [4]:
df = pd.read_csv("COVID-19 Survey Student Responses.csv")
df.head(10)

,ID,Region of residence,Age of Subject,Time spent on Online Class,Rating of Online Class experience,Medium for online class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Prefered social media platform,Time spent on TV,Number of meals per day,Change in your weight,Health issue during lockdown,Stress busters,Time utilized,"Do you find yourself more connected with your family, close friends , relatives ?",What you miss the most
0,R1,Delhi-NCR,21,2.0,Good,Laptop/Desktop,4.0,0.0,7.0,3.0,Linkedin,1,4,Increased,NO,Cooking,YES,YES,School/college
1,R2,Delhi-NCR,21,0.0,Excellent,Smartphone,0.0,2.0,10.0,3.0,Youtube,0,3,Decreased,NO,Scrolling through social media,YES,NO,Roaming around freely
2,R3,Delhi-NCR,20,7.0,Very poor,Laptop/Desktop,3.0,0.0,6.0,2.0,Linkedin,0,3,Remain Constant,NO,Listening to music,NO,YES,Travelling
3,R4,Delhi-NCR,20,3.0,Very poor,Smartphone,2.0,1.0,6.0,5.0,Instagram,0,3,Decreased,NO,Watching web series,NO,NO,"Friends , relatives"
4,R5,Delhi-NCR,21,3.0,Good,Laptop/Desktop,3.0,1.0,8.0,3.0,Instagram,1,4,Remain Constant,NO,Social Media,NO,NO,Travelling
5,R6,Delhi-NCR,21,0.0,Very poor,Smartphone,6.0,0.0,5.0,1.0,Youtube,0,1,Decreased,YES,Coding and studying for exams,NO,YES,School/college
6,R7,Delhi-NCR,19,2.0,Very poor,Smartphone,2.0,1.0,5.0,4.0,Instagram,0,3,Increased,NO,Watching web series,NO,YES,"Friends , relatives"
7,R8,Outside Delhi-NCR,19,2.0,Very poor,Tablet,1.0,1.0,10.0,5.0,Instagram,0,3,Increased,YES,Scrolling through social media,NO,YES,Eating outside
8,R9,Delhi-NCR,21,3.0,Very poor,Laptop/Desktop,4.0,1.0,8.0,2.0,Whatsapp,1,3,Increased,NO,Online surfing,NO,NO,"Friends , relatives"
9,R10,Outside Delhi-NCR,20,0.0,Very poor,Laptop/Desktop,1.0,0.5,8.0,5.0,Instagram,3,3,Decreased,YES,live stream watching,NO,NO,School/college

### 2.2. Mỗi dòng có ý nghĩa gì? Có vấn đề các dòng có ý nghĩa khác nhau không?

* Mỗi dòng thể hiện thông tin chi tiết sinh hoạt của học sinh/ sinh viên/ giảng viên sau tác động của COVID-19 đối với giáo dục và đời sống xã hội và sức khỏe tinh thần.
* **Không** có dòng nào có ý nghĩa khác nhau.

### 2.3. Dữ liệu có các dòng bị lặp không?

Kiểm tra việc này và lưu kết quả vào biến `have_duplicated_rows`. Biến này sẽ có giá trị `True` nếu dữ liệu có các dòng bị lặp và có giá trị `False` nếu ngược lại. Do ở đây cột `ID` mang tính định danh cho từng cá nhân nên ta sẽ kiểm tra xem thử có ID  nào trùng nhau không.

In [11]:
check_duplicated = set(df.ID.duplicated())

if True in check_duplicated:
    have_duplicated_rows = True
else:
    have_duplicated_rows = False
    
if (have_duplicated_rows == True):
    print('Có dòng dữ liệu bị lặp')
else:
    print('Không có dòng dữ liệu nào bị lặp')

Không có dòng dữ liệu nào bị lặp

<h3> 2.4. Mỗi cột có ý nghĩa gì?</h3>

|STT|Tên cột dữ liệu | <center>Mô tả<center> | Đơn vị |
|--|:------:| ---| --- |
|1|ID|<center>Mã định danh của từng người<center>|
|2|Region of residence| <center>Khu vực sinh sống<center>|
|3|Age of Subject|<center>Tuổi<center>| Năm
|4|Time spent on Online Class| <center>Thời gian học Online<center>| Giờ|
|5|Rating of Online Class experience|<center>Xếp loại kinh nghiệm học Online<center>|  | 
|6|Medium for online class|<center>Thiết bị sử dụng học Online<center>|  Giờ
|7|Time spent on self study|<center>Thời gian tự học<center>| Giờ |
|8|Time spent on fitness|<center>Thời gian thể dục, tập luyện<center>| Giờ |
|9|Time spent on sleep|<center>Thời gian ngủ<center>| Giờ |
|10|Time spent on social media|<center>Thời gian sử dụng MXH<center>| Giờ |
|11|Prefered social media platform|<center>Nền tảng MXH sử dụng<center>| |
|12|Time spent on TV|<center>Thời gian sử dụng TV<center>| Giờ |
|13|Number of meals per day|<center>Số bữa ăn trong ngày<center>| Lần |
|14|Change in your weight|<center>Dao động cân nặng<center>|  |
|15|Health issue during lockdown|<center>Có vấn đề gì về sức khỏe trong khoảng thời gian đóng cửa vì COVID-19 không?<center>|  |
|16|Stress busters|<center>Việc làm giúp xả stress<center>|  |
|17|Time utilized|<center>Thời gian được tối ưu không?<center>|  |
|18|Do you find yourself more connected with your family, close friends , relatives  ?|<center>Có cảm thấy được gắn kết nhiều hơn vớ gia đình, bạn bè không?<center>|  |
|19|What you miss the most|<center>Điều gì bạn hối tiếc nhất?<center>|



* **Thời gian cập nhật dữ liệu** 2021

<h3> 2.5. Với mỗi cột, dữ liệu phân bố như thế nào?</h3>

In [9]:
df.columns

Index(['ID', 'Region of residence', 'Age of Subject',
       'Time spent on Online Class', 'Rating of Online Class experience',
       'Medium for online class', 'Time spent on self study',
       'Time spent on fitness', 'Time spent on sleep',
       'Time spent on social media', 'Prefered social media platform',
       'Time spent on TV', 'Number of meals per day', 'Change in your weight',
       'Health issue during lockdown', 'Stress busters', 'Time utilized',
       'Do you find yourself more connected with your family, close friends , relatives  ?',
       'What you miss the most'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1182 entries, 0 to 1181
Data columns (total 19 columns):
 #   Column                                                                              Non-Null Count  Dtype
---  ------                                                                              --------------  -----
 0   ID                                                                                  1182 non-null   object
 1   Region of residence                                                                 1182 non-null   object
 2   Age of Subject                                                                      1182 non-null   int64
 3   Time spent on Online Class                                                          1182 non-null   float64
 4   Rating of Online Class experience                                                   1158 non-null   object
 5   Medium for online class                                                             1131 non-null   object
 6   Time spent on self study                                                            1182 non-null   float64
 7   Time spent on fitness                                                               1182 non-null   float64
 8   Time spent on sleep                                                                 1182 non-null   float64
 9   Time spent on social media                                                          1182 non-null   float64
 10  Prefered social media platform                                                      1182 non-null   object
 11  Time spent on TV                                                                    1182 non-null   object
 12  Number of meals per day                                                             1182 non-null   int64
 13  Change in your weight                                                               1182 non-null   object
 14  Health issue during lockdown                                                        1182 non-null   object
 15  Stress busters                                                                      1182 non-null   object
 16  Time utilized                                                                       1182 non-null   object
 17  Do you find yourself more connected with your family, close friends , relatives  ?  1182 non-null   object
 18  What you miss the most                                                              1182 non-null   object
dtypes: float64(5), int64(2), object(12)
memory usage: 175.6+ KB

3 Mỗi cột hiện đang có kiểu dữ liệu gì? Có cột nào có kiểu dữ liệu chưa phù hợpđể có thể xử lý tiếp hay không?

4 Với mỗi cột, các giá trị (dạng số, dạng phân loại) được phân bố như thế nào?

5 Có cần phải tiền xử lý dữ liệu hay không và nếu có thì nhóm sinh viên cần phải xử lý như thế nào?

<a name="3"></a>
## <font color=#0404B4>3. Mỗi cột hiện đang có kiểu dữ liệu gì? Có cột nào có kiểu dữ liệu chưa phù hợp?</font>

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1182 entries, 0 to 1181
Data columns (total 19 columns):
 #   Column                                                                              Non-Null Count  Dtype
---  ------                                                                              --------------  -----
 0   ID                                                                                  1182 non-null   object
 1   Region of residence                                                                 1182 non-null   object
 2   Age of Subject                                                                      1182 non-null   int64
 3   Time spent on Online Class                                                          1182 non-null   float64
 4   Rating of Online Class experience                                                   1158 non-null   object
 5   Medium for online class                                                             1131 non-null   object
 6   Time spent on self study                                                            1182 non-null   float64
 7   Time spent on fitness                                                               1182 non-null   float64
 8   Time spent on sleep                                                                 1182 non-null   float64
 9   Time spent on social media                                                          1182 non-null   float64
 10  Prefered social media platform                                                      1182 non-null   object
 11  Time spent on TV                                                                    1182 non-null   object
 12  Number of meals per day                                                             1182 non-null   int64
 13  Change in your weight                                                               1182 non-null   object
 14  Health issue during lockdown                                                        1182 non-null   object
 15  Stress busters                                                                      1182 non-null   object
 16  Time utilized                                                                       1182 non-null   object
 17  Do you find yourself more connected with your family, close friends , relatives  ?  1182 non-null   object
 18  What you miss the most                                                              1182 non-null   object
dtypes: float64(5), int64(2), object(12)
memory usage: 175.6+ KB

Ta thấy một số vấn đề cần giải quyết:

- Cột `Time spent on TV` là cột đúng ra có dạng dữ liệu numerical. Nên ta sẽ tiến hành xử lý các cột này để đưa chúng về đúng kiểu dữ liệu.

In [6]:
df['Time spent on TV'].unique()

array(['1', '0', '3', '0.5', 'n', '2', '4.5', '1.5', 'N', '4', '0.3', '5',
       'No tv', '0.1', '0.25', '6', '0.6', '7', '8', '15', ' ', '0.75',
       '2.5', '3.5', '0.4'], dtype=object)

Ta sẽ tiến hành xử lý các giá trị "No tv", "N", "n", và " " bằng cách quy đổi chúng về 0, tức là số giờ sử dụng TV là 0 giờ.

In [9]:
def conditions(x):
    if x=='No tv' or x=='n' or x=='N' or x==' ':
        return '0'
    else: 
        return x
    
df['Time spent on TV'] = df['Time spent on TV'].apply(conditions)

Cuối cùng, ta tiến hành ép kiểu cột `Time spent on TV` thành kiểu dữ liệu `float`.

In [11]:
df['Time spent on TV'] = df['Time spent on TV'].apply(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1182 entries, 0 to 1181
Data columns (total 19 columns):
 #   Column                                                                              Non-Null Count  Dtype
---  ------                                                                              --------------  -----
 0   ID                                                                                  1182 non-null   object
 1   Region of residence                                                                 1182 non-null   object
 2   Age of Subject                                                                      1182 non-null   int64
 3   Time spent on Online Class                                                          1182 non-null   float64
 4   Rating of Online Class experience                                                   1158 non-null   object
 5   Medium for online class                                                             1131 non-null   object
 6   Time spent on self study                                                            1182 non-null   float64
 7   Time spent on fitness                                                               1182 non-null   float64
 8   Time spent on sleep                                                                 1182 non-null   float64
 9   Time spent on social media                                                          1182 non-null   float64
 10  Prefered social media platform                                                      1182 non-null   object
 11  Time spent on TV                                                                    1182 non-null   float64
 12  Number of meals per day                                                             1182 non-null   int64
 13  Change in your weight                                                               1182 non-null   object
 14  Health issue during lockdown                                                        1182 non-null   object
 15  Stress busters                                                                      1182 non-null   object
 16  Time utilized                                                                       1182 non-null   object
 17  Do you find yourself more connected with your family, close friends , relatives  ?  1182 non-null   object
 18  What you miss the most                                                              1182 non-null   object
dtypes: float64(6), int64(2), object(11)
memory usage: 175.6+ KB

<a name="4"></a>
## <font color=#0404B4> 4. Với mỗi cột, các giá trị được phân bố như thế nào?</font>

### Với mỗi cột có kiểu dữ liệu dạng số (numerical), các giá trị được phân bố như thế nào?

Ở dữ liệu này, hiện có 8 cột thuộc nhóm numeric: `Age of Subject`, `Time spent on Online Class`, `Time spent on self study`, `Time spent on fitness`, `Time spent on sleep`, `Time spent on social media`, `Time spent on TV`, `Number of meals per day`.

In [23]:
pd.set_option('display.max_colwidth', 200)
numerical_cols = df[df.select_dtypes(exclude=['object']).columns]
numerical_cols.head(5)

,Age of Subject,Time spent on Online Class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Time spent on TV,Number of meals per day
0,21,2.0,4.0,0.0,7.0,3.0,1.0,4
1,21,0.0,0.0,2.0,10.0,3.0,0.0,3
2,20,7.0,3.0,0.0,6.0,2.0,0.0,3
3,20,3.0,2.0,1.0,6.0,5.0,0.0,3
4,21,3.0,3.0,1.0,8.0,3.0,1.0,4

Với mỗi cột numeric ta sẽ tính tỉ lệ % giá trị thiếu (từ 0 đến 100), min, max. Và lưu kết quả vào Dataframe `nume_col_profiles_df`.
Dataframe này gồm có:
- 3 dòng là `missing_ratio`, `min`, `max` lần lượt là tỉ lệ các giá trị thiếu mỗi cột, min và max.
- 8 cột là các thuộc tính thuộc kiểu dữ liệu **numerical**.

In [17]:
def missing_ratio(c):
    return  c.isna().sum()/len(df) * 100

def min(c):
    return c.min()

def max(c):
    return c.max()

nume_col_profiles_df = numerical_cols.agg([missing_ratio, min, max])
nume_col_profiles_df

,Age of Subject,Time spent on Online Class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Time spent on TV,Number of meals per day
missing_ratio,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,7.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0
max,59.0,10.0,18.0,5.0,15.0,10.0,15.0,8.0

### Với mỗi cột có kiểu dữ liệu dạng phân loại (categorical), các giá trị được phân bố như thế nào?

Ở dữ liệu này, hiện có 11 cột thuộc nhóm categorical: `ID`, `Region of residence`, `Rating of Online Class experience`, `Rating of Online Class experience`, `Medium for online class`, `Prefered social media platform`, `Change in your weight`, `Change in your weight`, `Health issue during lockdown`, `Stress busters`, `Time utilized`, `Do you find yourself more connected with your family, close friends , relatives  ?`, `What you miss the most`.

In [19]:
pd.set_option('display.max_colwidth', 200)
object_cols = df[df.select_dtypes(include=['object']).columns]
object_cols.head(5)

,ID,Region of residence,Rating of Online Class experience,Medium for online class,Prefered social media platform,Change in your weight,Health issue during lockdown,Stress busters,Time utilized,"Do you find yourself more connected with your family, close friends , relatives ?",What you miss the most
0,R1,Delhi-NCR,Good,Laptop/Desktop,Linkedin,Increased,NO,Cooking,YES,YES,School/college
1,R2,Delhi-NCR,Excellent,Smartphone,Youtube,Decreased,NO,Scrolling through social media,YES,NO,Roaming around freely
2,R3,Delhi-NCR,Very poor,Laptop/Desktop,Linkedin,Remain Constant,NO,Listening to music,NO,YES,Travelling
3,R4,Delhi-NCR,Very poor,Smartphone,Instagram,Decreased,NO,Watching web series,NO,NO,"Friends , relatives"
4,R5,Delhi-NCR,Good,Laptop/Desktop,Instagram,Remain Constant,NO,Social Media,NO,NO,Travelling

Với mỗi cột categorical, ta tính tỉ lệ % giá trị thiếu (từ 0 đến 100), số lượng giá trị khác nhau (không xét giá trị thiếu), list/array các giá trị khác nhau (không xét giá trị thiếu). Kết quả được lưu vào dataframe `cate_col_profiles_df`. Dataframe này có 3 dòng là `missing_ratio`, `num_diff_vals`, `ratio_diff_vals`; và có 7 cột là các thuộc tính có kiểu dữ liệu **categorical**.

In [21]:
def num_diff_vals(col):
    return len(col.value_counts())

def ratio_diff_vals(col):
    return np.round(col.value_counts(normalize=True),2).to_dict()

cate_col_profiles_df=object_cols.agg([missing_ratio,num_diff_vals,ratio_diff_vals])
cate_col_profiles_df

,ID,Region of residence,Rating of Online Class experience,Medium for online class,Prefered social media platform,Change in your weight,Health issue during lockdown,Stress busters,Time utilized,"Do you find yourself more connected with your family, close friends , relatives ?",What you miss the most
missing_ratio,0.0,0.0,2.030457,4.314721,0.0,0.0,0.0,0.0,0.0,0.0,0.0
num_diff_vals,1182,2,5,5,16,3,2,86,2,2,51
ratio_diff_vals,"{'R1': 0.0, 'R785': 0.0, 'R801': 0.0, 'R800': 0.0, 'R799': 0.0, 'R798': 0.0, 'R797': 0.0, 'R796': 0.0, 'R795': 0.0, 'R794': 0.0, 'R793': 0.0, 'R792': 0.0, 'R791': 0.0, 'R790': 0.0, 'R789': 0.0, 'R...","{'Delhi-NCR': 0.61, 'Outside Delhi-NCR': 0.39}","{'Very poor': 0.36, 'Average': 0.33, 'Good': 0.2, 'Excellent': 0.08, 'Poor': 0.03}","{'Laptop/Desktop': 0.48, 'Smartphone': 0.48, 'Tablet': 0.03, 'Any Gadget': 0.0, 'Smartphone or Laptop/Desktop': 0.0}","{'Instagram': 0.3, 'Whatsapp': 0.28, 'Youtube': 0.27, 'Linkedin': 0.05, 'Facebook': 0.04, 'Twitter': 0.02, 'None': 0.01, 'Snapchat': 0.01, 'Reddit': 0.0, 'Telegram': 0.0, 'Omegle': 0.0, 'Elyment':...","{'Remain Constant': 0.45, 'Increased': 0.37, 'Decreased': 0.18}","{'NO': 0.86, 'YES': 0.14}","{'Listening to music': 0.23, 'Online gaming': 0.15, 'Watching web series': 0.09, 'Reading books': 0.07, 'Scrolling through social media': 0.06, 'Sleeping': 0.06, 'Online surfing': 0.04, 'Meditatio...","{'NO': 0.51, 'YES': 0.49}","{'YES': 0.7, 'NO': 0.3}","{'School/college': 0.32, 'Friends , relatives': 0.19, 'Travelling': 0.15, 'Roaming around freely': 0.13, 'Eating outside': 0.09, 'Colleagues': 0.06, 'Nothing': 0.01, 'ALL': 0.01, 'All': 0.01, 'Gym..."

# C. Khám phá mối quan hệ trong dữ liệu